#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ShoppingCart.Resource", IsApplication=true)]

namespace ShoppingCart
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int EditTextCdBarras = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int EditTextNombreProducto = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int EditTextPrecioProducto = 2131034121;
			
			// aapt resource value: 0x7f05000f
			public const int LVProducts = 2131034127;
			
			// aapt resource value: 0x7f050003
			public const int TextViewMostrarIDProducto = 2131034115;
			
			// aapt resource value: 0x7f05000e
			public const int btnConsultar = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int btnEliminar = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int btnGuardar = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int btnLimpiar = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int btnModificar = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int scrollView1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int textViewIdProducto = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int textViewNameProduct = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int textViewTitleCdBarras = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int textViewTitlePrecioProducto = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int textpro = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int MissingFieldsError = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
